### ISSUE TITLE
Is the dev release still needed

### ISSUE THREAD

**Issue by GreenGremlin** [svengau/chrome-process-monitor#1]
It's been over a year since this extension was released, is the dev release still necessary? I tried installing it on mainline Chrome, but it only showed "Loading...". What experimental feature is it relying on?

**Comment by svengau** [comment]
Hi @GreenGremlin, yes the dev release is still necessary, this plugin needs the processes extensions to run: https://developer.chrome.com/extensions/processes

**Comment by GreenGremlin** [comment]
Ok, good to know. This extension seems like it will be really convenient, once it works in the mainline. It may not be a bad idea to add a link to in the extension description, just as a quick reference.
